quote/urls.py
from django.urls import path
from . import views

app_name = 'quote'
urlpatterns = [
    path('quote-main/', views.HomeView.as_view(), name='main'),
    path('quote-list/', views.QuoteListView.as_view(), name='quote-list'),
    path('quote-create/', views.QuoteCreateView.as_view(), name='quote-create'),
    path('<int:pk>/detail', views.QuoteDetailView.as_view(), name='quote-detail'),
    path('<int:pk>/edit', views.QuoteEditView.as_view(), name='quote-edit'),
    path('<int:pk>/del', views.QuoteDeleteView.as_view(), name='quote-del'),
    path('<int:pk>/mail', views.send_email_quote, name='quote-mail'),
]

quote/models.py
import random
import string

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Sum, F, Case, When
from django.urls import reverse
from django.utils.text import slugify

from organization.models import Organization
from product.models import Product


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class Quote(models.Model):
    """
    quote will be create by user
    """

    class Meta:
        verbose_name = "پیش فاکتور"
        verbose_name_plural = "پیش فاکتور ها"

    organization_name = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name='انتخاب سازمان')
    creator = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name='کاربر ثبت کننده')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug())
        super(Quote, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.organization_name} ({self.created_at}) {self.creator}"

    def get_absolute_url(self):
        return reverse('quote:quote-detail', kwargs={'pk': self.pk})

    def get_total_quantity(self):
        return self.quote_item.all().aggregate(Sum('quantity')).get('quantity__sum', 0)

    def total_price(self):
        return self.quote_item.all().annotate(each_item_price=F('quantity') * F('product_name__price')) \
            .aggregate(Sum('each_item_price'))['each_item_price__sum']

    def get_quote_discount(self):
        return self.quote_item.all().annotate(
            total_price=F('quantity') * F('product_name__price')).annotate(
                total_discount=(F('discount') * F('total_price') / 100)) \
            .aggregate(Sum('total_discount'))['total_discount__sum']

    def get_quote_tax(self):
        return self.quote_item.all().annotate(
            total_base_price=F('quantity') * F('product_name__price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_tax=Case(
                When(product_name__tax=True, then=(F('total_price') * 9 / 100)),
                When(product_name__tax=False, then=0),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_tax'))['total_tax__sum']

    def total_price_with_tax(self):
        return self.quote_item.all().annotate(
            total_base_price=F('quantity') * F('product_name__price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_price=Case(
                When(product_name__tax=True, then=F('total_price') + (F('total_price') * 9 / 100)),
                When(product_name__tax=False, then=F('total_price')),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_price'))['total_price__sum']

    # def total_price_with_tax(self):
    #     ip = self.quote_item.all().annotate(each_item_price=F('quantity') * F('product_name__price')) \
    #         .aggregate(Sum('each_item_price'))['each_item_price__sum'] or 0
    #     return ip + ((ip * 9) / 100)


class QuoteItem(models.Model):
    """
    items in a quote
    """

    class Meta:
        verbose_name = "دستگاه مورد درخواست"
        verbose_name_plural = "دستگاه های مورد درخواست"

    quote = models.ForeignKey(Quote, on_delete=models.CASCADE, verbose_name='پیش فاکتور', related_name='quote_item')
    product_name = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='انتخاب دستگاه')
    quantity = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1)], verbose_name='تعداد')
    discount = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)], verbose_name='درصد تخفیف')

    def each_item_price(self):
        return self.product_name.price * self.quantity

quote/forms.py
from django.forms import inlineformset_factory

from quote import models


QuoteItemFormSet = inlineformset_factory(
    models.Quote,
    models.QuoteItem,
    fields=('product_name', 'quantity', 'discount')
)

quote/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, TemplateView, DetailView, UpdateView, FormView, DeleteView
from django.views.generic.detail import SingleObjectMixin

import organization
from quote import models, forms, tasks


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = 'login'
    template_name = 'quote/main.html'


class QuoteListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = models.Quote
    paginate_by = 5
    template_name = 'quote/quote_list.html'

    def get_queryset(self):
        return models.Quote.objects.filter(
            creator=self.request.user
        )


class QuoteCreateView(LoginRequiredMixin, CreateView):
    login_url = 'login'
    model = models.Quote
    template_name = 'quote/quote_create.html'
    fields = [
        'organization_name',
    ]

    def get_form(self, *args, **kwargs):
        form = super(organization.views.CreateView, self).get_form(*args, **kwargs)
        form.fields['organization_name'].queryset = models.Organization.objects.filter(creator=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.creator = self.request.user
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'پیش فاکتور اضافه شد.'
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('quote:quote-edit', kwargs={'pk': self.object.pk})


class QuoteDetailView(LoginRequiredMixin, DetailView):
    model = models.Quote
    template_name = 'quote/quote_detail.html'

    def get_queryset(self):
        return models.Quote.objects.filter(
            creator=self.request.user
        )


class QuoteEditView(LoginRequiredMixin, SingleObjectMixin, FormView):
    model = models.Quote
    template_name = 'quote/quote_edit.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=models.Quote.objects.all())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=models.Quote.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return forms.QuoteItemFormSet(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'تغییرات ذخیره شد.'
        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('quote:quote-detail', kwargs={'pk': self.object.pk})


class QuoteDeleteView(DeleteView):
    """
    delete a quote
    """
    model = models.Quote
    success_url = reverse_lazy('quote:quote-list')

    def get_queryset(self):
        return models.Quote.objects.filter(
            creator=self.request.user
        )


@login_required
def send_email_quote(request, pk):
    quote = models.Quote.objects.get(pk=pk, creator=request.user)
    content = render_to_string('quote/quote_detail.html', {'object': quote})
    sender = request.user.username
    receiver = quote.organization_name.email
    if quote:
        tasks.email_quote_task.delay(content, sender, receiver)
        messages.success(request, 'ایمیل ارسال شد')
    return redirect('/quote/quote-list/')

quote/templates/quote/main.html
{% extends 'organization/base.html' %}

{% block title %}صفحه اصلی پیش فاکتور{% endblock %}

{% block content %}
    <div class="container-fluid" dir="rtl">
        <div class="d-flex align-items-center py-5">
            <div class="col-12 col-md-6 col-lg-4 mx-auto">

                <h3>بخش پیش فاکتور ها</h3>
                <a href="{% url 'quote:quote-list' %}" role="button" class="btn btn-primary w-100 mb-2">لیست پیش فاکتور
                    ها</a>
                <a href="{% url 'quote:quote-create' %}" role="button" class="btn btn-secondary w-100">پیش فاکتور
                    جدید</a>
            </div>
        </div>
    </div>


{% endblock content %}

quote/templates/quote/quote_confirm_delete.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    تایید حذف
{% endblock %}
{% block content %}
    <div class="container">
        <form dir="rtl" method="post">
            {% csrf_token %}
            <div class="form-row">
                <p>فاکتور انتخاب شده حذف شود؟</p>
                <input class="ml-5" type="submit" value="Confirm">
            </div>
            <div class="form-row">
                <p>{{ object }}</p>
            </div>
        </form>
    </div>
{% endblock %}

quote/templates/quote/quote_create.html
{% extends 'organization/base.html' %}

{% block title %}پیش فاکتور جدید{% endblock %}

{% block content %}
    <div class="container-fluid" dir="rtl">
        <div class="d-flex align-items-center py-5">
            <div class="col-12 col-md-6 col-lg-4 mx-auto">

                <form action="" method="post">
                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}

                    {% csrf_token %}

                    {{ form.non_form_errors }}

                    {% for field in form %}
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                    {% endfor %}

                    <p class="pt-2">
                        <button type="submit" class="btn btn-primary w-100 mb-2">ثبت پیش فاکتور</button>
                        <a href="{% url 'quote:main' %}" role="button" class="btn btn-secondary w-100">لغو</a>
                    </p>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

quote/templates/quote/quote_detail.html
{% extends 'organization/base.html' %}
{% block title %}{{ quote.organization_name }}{% endblock %}
{% block content %}
    <table class="table table-striped" dir="rtl">
        <thead>
        <tr>
            <th scope="col">دستگاه</th>
            <th scope="col">تعداد</th>
            <th scope="col">تخفیف</th>
            <th scope="col">قیمت</th>
            <th scope="col">مشمول مالیات است؟</th>
        </tr>
        </thead>
        {% for qi in object.quote_item.all %}
            <tbody>
            <tr>
                <td>{{ qi.product_name }}</td>
                <td>{{ qi.quantity }}</td>
                <td>{{ qi.discount }}</td>
                <td>{{ qi.product_name.price }}</td>
                {% if qi.product_name.tax %}
                    <td>بله</td>
                {% else %}
                    <td>خیر</td>
                {% endif %}
            </tr>
            </tbody>
        {% empty %}
            <li dir="rtl">هنوز هیچ دستگاهی ثبت نشده است</li>
        {% endfor %}
    </table>
    <table class="table table-striped" dir="rtl">
        {% if form.forms|length < 1 %}
            <thead>
            <tr>
                <th scope="col">مجموع اقلام</th>
                <th scope="col">قیمت پایه</th>
                <th scope="col">تخفیف ٪</th>
                <th scope="col">مالیات ٪</th>
                <th scope="col">قیمت پایانی</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ quote.get_total_quantity }}</td>
                <td>{{ quote.total_price }}</td>
                <td>{{ quote.get_quote_discount }}</td>
                <td>{{ quote.get_quote_tax }}</td>
                <td>{{ quote.total_price_with_tax }}</td>
            </tr>
            </tbody>
        {% endif %}
    </table>
    <p>
        <a href="{% url 'quote:quote-list' %}" role="button" class="btn btn-secondary w-100">لیست پیش فاکتور
            ها</a>
    </p>


{% endblock content %}

quote/templates/quote/quote_edit.html
{% extends 'organization/base.html' %}

{% block title %}ویرایش پیش فاکتور  {{ quote.organization_name }}{% endblock %}

{% block content %}
    <div class="container-fluid" dir="rtl">
        <div class="d-flex align-items-center py-5">
            <div class="col-12 col-md-6 col-lg-4 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">

                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}

                    {% csrf_token %}

                    {{ form.management_form }}
                    {{ form.non_form_errors }}

                    <h3>ویرایش اقلام</h3>
                    {% for qi_form in form.forms %}
                        <hr>
                        <h5>
                            {% if qi_form.instance.id %}
                                دستگاه: {{ qi_form.instance.title|title }}
                            {% else %}
                                {% if form.forms|length > 1 %}
                                    دستگاه جدید
                                {% else %}
                                    پیش فاکتور خالی است.
                                {% endif %}
                            {% endif %}
                        </h5>
                        {% for hidden_field in qi_form.hidden_fields %}
                            {{ hidden_field.errors }}
                        {% endfor %}
                        <table>
                            {{ qi_form.as_table }}
                        </table>
                    {% endfor %}
                    <hr>
                    <p>
                        <button type="submit" value="Update collection" class="btn btn-primary w-100 mb-3">ویرایش اقلام
                        </button>
                        <a href="{% url 'quote:quote-detail' pk=quote.pk %}" role="button" class="btn btn-secondary w-100">لغو</a>
                    </p>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

quote/templates/quote/quote_list.html
{% extends 'organization/base.html' %}
{% block title %}لیست فاکتور ها{% endblock %}
{% block content %}
    <table class="table table-striped" dir="rtl">
        <thead>
        <tr>
            <th scope="col">پیش فاکتور برای</th>
            <th scope="col">ارسال ایمیل</th>
            <th scope="col">حذف پیش فاکتور</th>
            <th scope="col">ویرایش پیش فاکتور</th>
        </tr>
        </thead>

        {% for q in quote_list %}
            <tbody>
            <tr>
                <td>
                    <a class="text-reset" href="{{ q.get_absolute_url }}">{{ q.organization_name }}</a>
                </td>
                <td><a href="{% url 'quote:quote-mail' pk=q.pk %}">📧</a></td>
                <td><a href="{% url 'quote:quote-del' pk=q.pk %}">❌</a></td>
                <td><a href="{% url 'quote:quote-edit' pk=q.pk %}">✏</a></td>
            </tr>
            </tbody>
        {% empty %}
            <li dir="rtl">هنوز هیچ گزارشی ثبت نشده است</li>
        {% endfor %}
    </table>

{% endblock content %}