organization/urls.py
from django.urls import path
from . import views

app_name = 'organization'
urlpatterns = [
    path('new/', views.CreateNew.as_view(), name='new'),
    path('<slug:slug>/', views.OrganizationDetailView.as_view(), name='detail'),
    path('edit/<slug:slug>/', views.OrganizationEditView.as_view(), name='edit'),
    path('<slug:slug>/delete/', views.OrganizationDeleteView.as_view(), name='delete')
]

organization/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils.text import slugify

from product import models as product_models

phone_regex = RegexValidator(regex=r"^[0][9]\d{9}$", message='شماره اشتباه است.')
organ_phone_regex = RegexValidator(regex=r"^0[0-9]{2,}[0-9]{7,}$", message='شماره اشتباه است.')


class Organization(models.Model):
    """
    users will create organizations
    """
    class Meta:
        verbose_name = "سازمان"
        verbose_name_plural = "سازمان ها"

    name = models.CharField(max_length=100, unique=True,
                            error_messages={'unique': "این نام در سیستم ثبت شده است."}, verbose_name='نام سازمان')
    province = models.CharField(max_length=100, verbose_name='استان')
    phone_number = models.CharField(unique=True, validators=[organ_phone_regex], max_length=11,
                                    verbose_name='تلفن سازمان')
    number_of_employees = models.PositiveIntegerField(verbose_name='تعداد کارمندان')
    organization_product = models.ManyToManyField(product_models.OrganizationProduct, verbose_name='محصولات تولیدی')
    audience_full_name = models.CharField(max_length=200, verbose_name='نام و نام خانوادگی مخاطب')
    audience_phone_number = models.CharField(validators=[phone_regex], max_length=11, verbose_name='تلفن مخاطب')
    email = models.EmailField(unique=True, verbose_name='ایمیل')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    creator = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name='کاربر ثبت کننده')
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.phone_number + "-" + self.email)
        super(Organization, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/"

    def suggestion(self):
        op = product_models.OrganizationProduct.objects.all()
        return product_models.Product.objects.filter(can_use_for__organization__organization_product__in=op).distinct()

    def __str__(self):
        return self.name

organization/forms.py
from django import forms
from . import models


class Organization(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = (
            'name',
            'province',
            'phone_number',
            'number_of_employees',
            'organization_product',
            'audience_full_name',
            'audience_phone_number',
            'email',
        )

organization/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from . import models, forms, serializers


class OrganizationViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and editing user organizations.
    """
    serializer_class = serializers.OrganizationSerializer
    permission_classes = [IsAuthenticated]
    queryset = models.Organization.objects.all()

    def get_queryset(self):
        user_organization = super().get_queryset()
        return user_organization.filter(creator=self.request.user)


class CreateNew(LoginRequiredMixin, CreateView):
    """
    user create new organizations
    """
    login_url = 'login'
    model = models.Organization
    form_class = forms.Organization

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class OrganizationList(LoginRequiredMixin, ListView):
    """
    list of all organizations created by a user
    """
    login_url = 'login'
    model = models.Organization
    paginate_by = 5

    def get_queryset(self):
        return models.Organization.objects.filter(
            creator=self.request.user
        )


class OrganizationEditView(LoginRequiredMixin, UpdateView):
    """
    update organization's info
    """
    model = models.Organization
    form_class = forms.Organization
    login_url = 'login'
    template_name = 'organization/organization_form.html'

    def get_queryset(self):
        return models.Organization.objects.filter(
            creator=self.request.user
        )


class OrganizationDeleteView(LoginRequiredMixin, DeleteView):
    """
    delete a organization
    """
    model = models.Organization
    login_url = 'login'
    success_url = "/"

    def get_queryset(self):
        return models.Organization.objects.filter(
            creator=self.request.user
        )


class OrganizationDetailView(LoginRequiredMixin, DetailView):
    """
    details of a organization
    """
    model = models.Organization
    login_url = 'login'

    def get_queryset(self):
        return models.Organization.objects.filter(
            creator=self.request.user
        )

organization/templates/organization/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>
        {% block page_header_title %}
        {% endblock %}
    </title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #af51c3;">
        <div class="container" dir="rtl">
            <a class="navbar-brand" href="{% url 'home' %}">🏠</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li>
                        <a class="nav-link" href="{% url 'organization:new' %}">ایجاد سازمان</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'quote:main' %}">پیش فاکتور ها</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav mr-auto">
                    {% if not user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'login' %}">ورود</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'logout' %}">خروج</a>
                        </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li>
                            <p class="nav-link">{{ request.user.username }}</p>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
{# Django's messages #}
<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissible">
                        {{ message }}
                        <button type="button" data-dismiss="alert" class="close">&times;</button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% block content %}YOUR CONTENT GOES HERE{% endblock %}
</div>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

{% block page_scripts %}{% endblock %}

<footer class="page-footer fixed-bottom font-small blue" style="background-color: #5d56cd;">

    <div class="footer-copyright text-center py-3">
        <span>© CRM template</span>
        <a href="#">🔝</a>
    </div>

</footer>
</body>
</html>

organization/templates/organization/organization_confirm_delete.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    تایید حذف
{% endblock %}
{% block content %}
    <div class="container">
        <form dir="rtl" method="post">
            {% csrf_token %}
            <div class="form-row">
                <p>سازمان انتخاب شده حذف شود؟</p>
                <input class="ml-5" type="submit" value="Confirm">
            </div>
            <div class="form-row">
                <p>{{ object }}</p>
            </div>
        </form>
    </div>
{% endblock %}

organization/templates/organization/organization_detail.html
{% extends 'organization/base.html' %}
{% block page_header_title %}
    {{ object.name }}
{% endblock %}
{% block content %}
    <div class="container" dir="rtl">
        <div class="row">
        </div>
        <div class="row">
            <table style="width:68%" dir="rtl">
                <tr style="color: #0bba98">
                    <th class="">مشخصات سازمان</th>
                </tr>
                <tr>
                    <th class="ml-5">نام سازمان</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th>استان</th>
                    <td>{{ object.province }}</td>
                </tr>
                <tr>
                    <th>تلفن</th>
                    <td>{{ object.phone_number }}</td>
                </tr>
                <tr>
                    <th>تعداد کارگران</th>
                    <td>{{ object.number_of_employees }}</td>
                </tr>
                <tr>
                    <th>محصولات سازمان</th>
                    <td dir="">{% for p in object.organization_product.all %}{{ p }},{% endfor %}</td>
                </tr>
                <tr>
                    <th>ایمیل</th>
                    <td>{{ object.email }}</td>
                </tr>
            </table>
        </div>
        <div class="row mt-5">
            <table style="width:60%" dir="rtl">
                <tr style="color: #0bba98">
                    <th class="">مشخصات مخاطب</th>
                </tr>
                <tr>
                    <th>نام مخاطب</th>
                    <td>{{ object.audience_full_name }}</td>
                </tr>
                <tr>
                    <th>تلفن مخاطب</th>
                    <td>{{ object.audience_phone_number }}</td>
                </tr>
            </table>
        </div>
        <div class="row mt-5 mb-4">
            <table style="width:60%" dir="rtl">
                <tr>
                    <th style="color: #0bba98" class="">محصولات پیشنهادی</th>
                    <td>{% for s in object.suggestion %}{{ s }},{% endfor %}</td>
                </tr>
            </table>
        </div>
    </div>
    <table class="table table-striped" dir="rtl">
        <thead>
        <tr>
            <th scope="col">لیست پیگیری های ثبت شده</th>
            <th scope="col">تاریخ ثبت</th>
            <th scope="col">حذف گزارش</th>
        </tr>
        </thead>

        {% for followup in object.followup_set.all %}
            <tbody>
            <tr>
                <td>
                    <a href="{% url 'followup:detail' followup.slug %}">{{ followup.descriptions | truncatechars:15 }}</a>
                </td>
                <td>{{ followup.created_at.date }}</td>
                <td><a href="{% url 'followup:delete' followup.slug %}">❌</a></td>
            </tr>
            </tbody>
        {% empty %}
            <li dir="rtl">هنوز هیچ گزارشی ثبت نشده است</li>
        {% endfor %}
    </table>


{% endblock %}

organization/templates/organization/organization_form.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    سازمان
{% endblock %}
{% block content %}
    <div class="container">
        <form dir="rtl" method="post">
            {% csrf_token %}
            <div class="form-row">
                <table>
                    {{ form }}
                </table>
            </div>
            <div class="form-row">
                <div class="form-group">
                    <button id="create_new" type="submit" class="btn btn-primary">ذخیره</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

organization/templates/organization/organization_list.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    لیست سازمان ها
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <table class="table table-striped" dir="rtl">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">نام سازمان</th>
            <th scope="col">ثبت کننده</th>
            <th scope="col">مخاطب</th>
            <th scope="col">ویرایش</th>
            <th scope="col">ثبت پیگیری</th>
            <th scope="col">حذف</th>
        </tr>
        </thead>
        {% for org in object_list %}
            {% if org.creator == request.user %}
                <tbody>
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'organization:detail' slug=org.slug %}">{{ org.name }}</a></td>
                    <td>{{ org.creator }}</td>
                    <td>{{ org.audience_full_name }}</td>
                    <td><a href="{% url 'organization:edit' slug=org.slug %}">📝</a></td>
                    <td><a href="{% url 'followup:new' org.pk %}">📝</a></td>
                    <td><a href="{% url 'organization:delete' slug=org.slug %}">❌</a></td>
                </tr>
            {% endif %}
        {% empty %}
            <li dir="rtl">هنوز هیچ سازمانی ثبت نشده است</li>
        {% endfor %}
    {% endif %}
</table>
    {% include 'organization/pagination.html' %}
{% endblock %}

organization/templates/organization/pagination.html
<div class="container justify-content-center" dir="rtl">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if object_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>