followup/urls.py
from django.urls import path
from . import views

app_name = 'followup'
urlpatterns = [
    path('new/<int:organization_pk>', views.CreateNew.as_view(), name='new'),
    path('<slug:slug>/', views.FollowUpDetailView.as_view(), name='detail'),
    path('<slug:slug>/delete/', views.FollowUpDeleteView.as_view(), name='delete')
]

followup/models.py
import random
import string

from django.db import models
from django.utils.text import slugify

from organization.models import Organization


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class FollowUp(models.Model):
    """
    user will write follow up for organizations
    """

    class Meta:
        verbose_name = "پیگیری"
        verbose_name_plural = "پیگیری ها"

    organization_name = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name='سازمان')
    descriptions = models.TextField(verbose_name='توضیحات')
    creator = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name='کاربر ثبت کننده')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug())
        super(FollowUp, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.organization_name.name} {self.created_at}'

followup/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DetailView, DeleteView
from rest_framework.status import HTTP_201_CREATED, HTTP_400_BAD_REQUEST

from followup import models
from organization.models import Organization


@method_decorator(csrf_exempt, name='dispatch')
class CreateNew(LoginRequiredMixin, CreateView):
    """
    user record followup for organizations
    """
    login_url = 'login'
    model = models.FollowUp
    template_name = 'followup/followup_create.html'
    fields = ('descriptions',)

    def form_invalid(self, form):
        error = form.errors
        return JsonResponse(data={
            'success': 'False',
            'error_message': 'لطفا فرم را به درستی تکمیل کنید!'
        }, status=HTTP_400_BAD_REQUEST)

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.organization_name = Organization.objects.get(pk=self.kwargs['organization_pk'])
        form.save()
        return JsonResponse(data={
            'success': 'True',
            'success_message': 'پیگیری ثبت شد!'
        }, status=HTTP_201_CREATED)

    def get_context_data(self, **kwargs):
        context = {
            'organization_obj': Organization.objects.get(pk=self.kwargs['organization_pk']),
        }
        return context


class FollowUpDetailView(LoginRequiredMixin, DetailView):
    """
    details of a followup
    """
    model = models.FollowUp
    login_url = 'login'

    def get_queryset(self):
        return models.FollowUp.objects.filter(
            creator=self.request.user
        )


class FollowUpDeleteView(LoginRequiredMixin, DeleteView):
    """
    delete a followup
    """
    model = models.Organization
    login_url = 'login'
    success_url = "/"

    def get_queryset(self):
        return models.FollowUp.objects.filter(
            creator=self.request.user
        )

followup/templates/followup/followup_confirm_delete.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    تایید حذف
{% endblock %}
{% block content %}
    <div class="container">
        <form dir="rtl" method="post">
            {% csrf_token %}
            <div class="form-row">
                <p>فرم پیگیری انتخاب شده حذف شود؟</p>
                <input class="ml-5" type="submit" value="Confirm">
            </div>
            <div class="form-row">
                <p>{{ object }}</p>
            </div>
        </form>
    </div>
{% endblock %}

followup/templates/followup/followup_create.html
{% extends 'organization/base.html' %}
{% load static %}
{% block page_header_title %}
    سازمان
{% endblock %}
{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('#record_btn').on('click', function (event) {
                var descriptions = $('#descriptions').val();
                $.ajax({
                    method: 'post',
                    url: '{% url 'followup:new' organization_obj.pk %}',
                    data: {
                        descriptions: descriptions
                    },
                    success: function (response) {
                        var success_message_div = $('#message-div')
                        success_message_div.empty()
                        var my_div = '<div class="alert alert-success">' + response.success_message + '<button type="button" data-dismiss="alert" class="close">&times;</button></div>'
                        success_message_div.append(my_div)
                    },
                    error: function (response) {
                        var error_message_div = $('#message-div')
                        error_message_div.empty()
                        var my_div = '<div class="alert alert-danger">' + response.responseJSON.error_message + '<button type="button" data-dismiss="alert" class="close">&times;</button></div>'
                        error_message_div.append(my_div)
                    },

                })
            });
        });
    </script>
{% endblock %}

followup/templates/followup/followup_detail.html
{% extends 'organization/base.html' %}
{% block page_header_title %}
    {{ object.name }}
{% endblock %}
{% block content %}
    <div class="container" dir="rtl">
        <div class="row">
        </div>
        <div class="row">
            <table style="width:68%" dir="rtl">
                <tr style="color: #0bba98">
                    <th class="">مشخصات گزارش</th>
                </tr>
                <tr>
                    <th class="ml-5">نام سازمان</th>
                    <td>{{ object.organization_name }}</td>
                </tr>
                <tr>
                    <th>ثبت کننده</th>
                    <td>{{ object.creator }}</td>
                </tr>
                <tr>
                    <th>تاریخ ثبت</th>
                    <td>{{ object.created_at.date }}</td>
                </tr>
                <tr>
                    <th>زمان ثبت</th>
                    <td>{{ object.created_at.time }}</td>
                </tr>
                <tr>
                    <th>متن گزارش</th>
                    <td>{{ object.descriptions }}</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}